### ISSUE TITLE
PHP Warning:  require(/home/madeny/lhttps/vendor/autoload.php):

### ISSUE THREAD

**Issue by Runneli** [madeny/lhttps#1]
PHP Warning:  require(/home/madeny/lhttps/vendor/autoload.php): failed to open stream: No such file or directory in /home/madeny/lhttps/lh on line 3
PHP Fatal error:  require(): Failed opening required '/home/madeny/lhttps/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/madeny/lhttps/lh on line 3

**Comment by madeny** [comment]
Sorry, I forgot to tell that you need to run composer install before you can run command.
