### ISSUE TITLE
PHP Warning:  file_put_contents(/home/runnel/lhttps/cert/cnf/v3.ext):

### ISSUE THREAD

**Issue by Runneli** [madeny/lhttps#2]
failed to open stream: Permission denied in /home/runnel/lhttps/src/Openssl.php on line 21
PHP Warning:  file_put_contents(/home/runnel/lhttps/cert/cnf/openssl.cnf): failed to open stream: Permission denied in /home/runnel/lhttps/src/Openssl.php on line 42
sh: 1: cannot create /home/runnel/lhttps/cert/live/process: Permission denied
sh: 1: cannot create /home/runnel/lhttps/cert/csr/process: Permission denied

**Comment by madeny** [comment]
Please make sure that the directory is owned by you!! this is due to permission.
